import { useParams } from "react-router-dom";
import ScrollToTop from "./ScrollToTop";
import HazardCard from "./HazardCard";
import { ALL_HAZARDS } from "./hazards";

const modules = import.meta.glob(
    "./content/**/*.mdx",
    {eager: true}
);

const posts = Object.values(modules).map(
    (mod: any) => ({
        metadata: mod.metadata,
        Component: mod.default
    })
);

const advisoryColors = {
    proceed: "green",
    mitigate: "yellow",
    monitor: "yellow",
    standby: "orange",
    suspend: "red",
    terminate: "pink",
} as const;

const severityColors = {
    none: "green",
    low: "yellow",
    moderate: "red",
    high: "pink",
} as const;

console.log(posts);

export default function PostsPage() {
    ScrollToTop();
    const {slug} = useParams();
    console.log(slug);

    function getConfidenceColor(confidence: number) {
        if (confidence >= 80) {
            return "pink"
        }

        if (confidence >= 60) {
            return "red"
        }

        if (confidence >= 40) {
            return "orange"
        }

        if (confidence >= 20) {
            return "yellow"
        }

        return "green"
    }

    function returnProbAsString(confidence: number) {
        if (confidence > 95) {
            return ">95%"
        }

        if (confidence < 5) {
            return "<5%"
        }

        return `${confidence}%`
    }

    function getRiskConfidenceAttribute(confidence: number) {
        if (confidence >= 95) {
            return "Very Likely"
        }

        if (confidence >= 80) {
            return "Likely"
        }

        if (confidence >= 60) {
            return "Trending Likely"
        }

        if (confidence >= 40) {
            return "Possible"
        }

        if (confidence >= 20) {
            return "Unlikely"
        }

        return "Very Unlikely"
    }

    function getConfidenceAttribute(confidence: number) {
        if (confidence >= 95) {
            return "Very High"
        }

        if (confidence >= 80) {
            return "High"
        }

        if (confidence >= 60) {
            return "Moderate"
        }

        if (confidence >= 40) {
            return "Slight"
        }

        if (confidence >= 20) {
            return "Low"
        }

        return "Very Low"
    }

    const post = posts.find(
        p => p.metadata.slug === slug
    );

    if (!post) {
        return <div>404 - Post not found</div>
    }

    const mergedHazards = 
        ALL_HAZARDS.map((hazard) => {
            const metadatahazard = 
                post.metadata.hazards.find(
                    (h: any) =>
                        h.hazard.toLowerCase() === hazard.id
                );

            return {
                ...hazard,
                
                status: metadatahazard
                    ? "active"
                    : "inactive",

                impact:
                    metadatahazard?.impact ??
                    "none",

                summary:
                    metadatahazard?.summary ??
                    "No impacts expected from this hazard.",

                color:
                    metadatahazard?.color ??
                    "green",

                fill:
                    metadatahazard?.fill ??
                    0,
            };
        });

    const Content = post.Component;

    return (
                <article className="post">
                    <h1>{post.metadata.title}</h1>
                    <p className="release-date">Released {new Date(post.metadata.date).toLocaleString()}</p>
                    <div className="backing-container">
                        <p className="big-header red">
                            <b>NOTICE</b>
                        </p>
                        <p className="red">
                            <b>THIS POST AND ITS CONTENT IS NOT AN OFFICIAL WEATHER SOURCE. THIS PAGE AND ITS CONTENT IS FOR INTERNAL USE BY THE AMATEUR RADIO CLUB @ UCF ONLY, AND SHOULD NOT BE USED AS AN AUTHORITATIVE SOURCE OF WEATHER.</b>
                        </p>
                        <p className="red">
                            <b>ALL PRODUCTS ISSUED ARE GENERATED BY THE WEATHER COMMITTEE IN THE ARC @ UCF CLUB. THESE PRODUCTS ARE PERTINENT TO CLUB ACTIVITIES. FORECASTS ARE OUR OWN, BUT UTILIZE WEATHER MODELS AND OFFICIAL INFORMATION FROM NOAA AND RELATED AGENCIES.</b>
                        </p>
                    </div>
                    <div className="backing-container">
                        <p className="summaryheader">
                            CONTENT SUMMARY
                        </p>
                        <p>{post.metadata.description}</p>
                    </div>
                    {(post.metadata.validfrom && post.metadata.validto && post.metadata.nextupdateby && post.metadata.type === "event") &&
                        <div className="backing-container">
                            <p className="timeheader">
                                FORECAST VALID
                            </p>
                            <p>{new Date(post.metadata.validfrom).toLocaleString()} to {new Date(post.metadata.validto).toLocaleString()}</p>
                            <p className="timeheader">
                                NEXT UPDATE BY
                            </p>
                            <p>{new Date(post.metadata.nextupdateby).toLocaleString()}</p>
                        </div>
                    }
                    <div className="backing-container">
                        <p className="confidenceheader">
                            FORECAST CONFIDENCE
                        </p>
                        <p className={`probs ${getConfidenceColor(post.metadata.confidence)}`}>
                            {post.metadata.confidence}%, {getConfidenceAttribute(post.metadata.confidence)}
                        </p>
                        <div className="meter-holder">
                            <progress className={`meter meter--${getConfidenceColor(post.metadata.confidence)}`} value={post.metadata.confidence} max={100}/>
                        </div>
                    </div>
                    {(post.metadata.problowrisk && post.metadata.probmodrisk && post.metadata.probhighrisk && post.metadata.type === "event") &&
                        <div className="backing-container">
                            <p className="confidenceheader">
                                CONFIDENCE PROBABILITY OF HAZARD RISK ISSUANCE
                            </p>
                            <p className="probs yellow">
                                Low: {returnProbAsString(post.metadata.problowrisk)}, {getRiskConfidenceAttribute(post.metadata.problowrisk)}
                            </p>
                            <div className="meter-holder">
                                <progress className="meter meter--yellow" value={post.metadata.problowrisk} max={100} />
                            </div>
                            <p className="probs red">
                                Moderate: {returnProbAsString(post.metadata.probmodrisk)}, {getRiskConfidenceAttribute(post.metadata.probmodrisk)}
                            </p>
                            <div className="meter-holder">
                                <progress className="meter meter--red" value={post.metadata.probmodrisk} max={100} />
                            </div>
                            <p className="probs pink">
                                High: {returnProbAsString(post.metadata.probhighrisk)}, {getRiskConfidenceAttribute(post.metadata.probhighrisk)}
                            </p>
                            <div className="meter-holder">
                                <progress className="meter meter--pink" value={post.metadata.probhighrisk} max={100} />
                            </div>
                        </div>
                    }
                    {post.metadata.type === "event" && (
                        <div className="status-banner">
                            <div className="section section--left">
                                <p>ADVISORY</p>
                                <div className="advisory">
                                    <div className={advisoryColors[post.metadata.advisory.toLowerCase() as keyof typeof advisoryColors]}>
                                        {post.metadata.advisory.toUpperCase()}
                                    </div>
                                </div>
                            </div>
                            <div className="section">
                                <p>RISK</p>
                                <div className="risk">
                                    <div className={severityColors[post.metadata.risk.toLowerCase() as keyof typeof severityColors]}>
                                        {post.metadata.risk.toUpperCase()}
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {post.metadata.type === "summary" && (
                        <div className="info-banner">
                            <div className="section">
                                <p>PRODUCT FOR</p>
                                <div className="info">
                                    {post.metadata.event.toUpperCase()}
                                </div>
                            </div>
                        </div>
                    )}

                    {post.metadata.type === "event" && (
                        <div className="hazard-container">
                            {mergedHazards.map((hazard) => (
                                <HazardCard 
                                    name={hazard.id}
                                    status={hazard.status}
                                    level={hazard.impact}
                                    sections={hazard.sections}
                                    used={hazard.fill}
                                    color={hazard.color}
                                    summary={hazard.summary}
                                />
                            ))}
                        </div>
                    )}
                    <Content />
                </article>
    )
}